version: '3.8'

services:
  wchatbot:
    container_name: wchatbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/wchatbot/src
      # - ./tokens:/wchatbot/tokens
      - ./logs:/wchatbot/logs
    ports:
      - '3000:3000'